from .angel_caido import AngelCaido
from .bandido import Bandido
from .demonio import Demonio
from .dragon import Dragon
from .enemy_base import Enemy
from .espiritu_vengativo import EspirituVengativo
from .gargola import Gargola
from .goblin import Goblin
from .golem import GolemDePiedra
from .huargo import Huargo
from .mage import Mago
from .nigromante import Nigromante
from .orc import Orc
from .skeleton import Skeleton
from .troll import Troll
